# Generated by Django 3.2.16 on 2022-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='feature_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='thumbnail_image'),
            preserve_default=False,
        ),
    ]
