# Generated by Django 3.2.16 on 2022-10-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycomment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='mycomment',
            old_name='post',
            new_name='CommentPost',
        ),
        migrations.RenameField(
            model_name='mycomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='mycomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='mycomment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mycomment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.mycomment'),
        ),
    ]
